### ISSUE TITLE
Close button not working

### ISSUE THREAD

**Issue by wenyuhaokikika** [simonschaufi/foundation-notify#1]
Close button not working,click × is not working
![image](https://user-images.githubusercontent.com/40107519/194499163-ba9fb98c-47c7-4055-abfe-7706746b96f4.png)
my code
JS
```
    $('.top-right').notify({
        type:'info',
        transition:'fade',
	    message: {text: 'Our server is not available from 5:00 p.m. to 7:00 a.m. Beijing time until Oct. 24.'},
        fadeOut:{enabled: true, delay: 60000}
    }).show();
```
html
```
<div class="notifications top-right"></div>
```

**Comment by simonschaufi** [comment]
This plugin is 8 years old already. Could you debug the code yourself please? I don't have the mood to spend much time on this code anymore
